"""initial schema

Revision ID: ef930323cb4b
Revises: 
Create Date: 2026-08-05 09:25:22.371054

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef930323cb4b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), server_default='hh', nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('openai_model', sa.Text(), nullable=False),
    sa.Column('openai_thinking_level', sa.Text(), nullable=True),
    sa.Column('openai_base_url', sa.Text(), nullable=True),
    sa.Column('openai_api_key_file', sa.Text(), nullable=False),
    sa.Column('min_required_score', sa.Integer(), server_default='3', nullable=False),
    sa.Column('scoring_prompt_file', sa.Text(), nullable=False),
    sa.Column('reply_prompt', sa.Text(), nullable=False),
    sa.Column('daily_apply_limit', sa.Integer(), server_default='50', nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('soft_deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipelines'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_audit_log_pipeline_id_pipelines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_pipeline_id'), ['pipeline_id'], unique=False)

    op.create_table('daily_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('auth_identifier', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_daily_limits_pipeline_id_pipelines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_limits')),
    sa.UniqueConstraint('pipeline_id', 'auth_identifier', 'date', name='uq_daily_limits_pipeline_auth_date')
    )
    with op.batch_alter_table('daily_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_limits_pipeline_id'), ['pipeline_id'], unique=False)

    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_reasoning', sa.Text(), nullable=True),
    sa.Column('score_error', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('cover_letter_error', sa.Text(), nullable=True),
    sa.Column('reply_status', sa.Text(), nullable=True),
    sa.Column('reply_error', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.Text(), nullable=True),
    sa.Column('manual_skip', sa.Integer(), server_default='0', nullable=False),
    sa.Column('manual_skip_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('soft_deleted_at', sa.Text(), nullable=True),
    sa.CheckConstraint("reply_status IN ('pending','replied','skipped','error')", name=op.f('ck_vacancies_reply_status')),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_vacancies_pipeline_id_pipelines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancies')),
    sa.UniqueConstraint('pipeline_id', 'external_id', name='uq_vacancies_pipeline_external'),
    sa.UniqueConstraint('pipeline_id', 'position_index', name='uq_vacancies_pipeline_position')
    )
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancies_pipeline_id'), ['pipeline_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancies_pipeline_id'))

    op.drop_table('vacancies')
    with op.batch_alter_table('daily_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_limits_pipeline_id'))

    op.drop_table('daily_limits')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_pipeline_id'))

    op.drop_table('audit_log')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
